source 'https://rubygems.org'

gem 'json_api_client'
gem 'gram_v2_client', git: 'https://github.com/gadzorg/gram2_api_client_ruby.git'
gem 'gorg_service'
gem 'gorg_message_sender'
gem 'gram_v1_client'
gem 'net-ldap'
gem 'activeldap'
gem 'byebug'
